// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeguimientoAcademico.App.Persistencia;

namespace SeguimientoAcademico.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211002015645_Entidades")]
    partial class Entidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Maestro")
                        .HasColumnType("int");

                    b.Property<int?>("SugerenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Tarea")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SugerenciaId");

                    b.ToTable("Historias");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("genero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Sugerencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sugerencias");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Estudiante", b =>
                {
                    b.HasBaseType("SeguimientoAcademico.App.Dominio.Persona");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FamiliarId")
                        .HasColumnType("int");

                    b.Property<string>("Grado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HistoriaId")
                        .HasColumnType("int");

                    b.Property<float>("Latitud")
                        .HasColumnType("real");

                    b.Property<float>("Longitud")
                        .HasColumnType("real");

                    b.Property<int?>("MaestroId")
                        .HasColumnType("int");

                    b.Property<string>("MateriasInscritas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.HasIndex("FamiliarId");

                    b.HasIndex("HistoriaId");

                    b.HasIndex("MaestroId");

                    b.HasIndex("TutorId");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.FamiliarDesignado", b =>
                {
                    b.HasBaseType("SeguimientoAcademico.App.Dominio.Persona");

                    b.Property<string>("Parentesco")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("FamiliarDesignado");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Maestro", b =>
                {
                    b.HasBaseType("SeguimientoAcademico.App.Dominio.Persona");

                    b.Property<string>("MateriaAsignada")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Maestro");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Tutor", b =>
                {
                    b.HasBaseType("SeguimientoAcademico.App.Dominio.Persona");

                    b.Property<string>("MateriaAsignada")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tutor_MateriaAsignada");

                    b.HasDiscriminator().HasValue("Tutor");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Historia", b =>
                {
                    b.HasOne("SeguimientoAcademico.App.Dominio.Sugerencia", "Sugerencia")
                        .WithMany()
                        .HasForeignKey("SugerenciaId");

                    b.Navigation("Sugerencia");
                });

            modelBuilder.Entity("SeguimientoAcademico.App.Dominio.Estudiante", b =>
                {
                    b.HasOne("SeguimientoAcademico.App.Dominio.FamiliarDesignado", "Familiar")
                        .WithMany()
                        .HasForeignKey("FamiliarId");

                    b.HasOne("SeguimientoAcademico.App.Dominio.Historia", "Historia")
                        .WithMany()
                        .HasForeignKey("HistoriaId");

                    b.HasOne("SeguimientoAcademico.App.Dominio.Maestro", "Maestro")
                        .WithMany()
                        .HasForeignKey("MaestroId");

                    b.HasOne("SeguimientoAcademico.App.Dominio.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId");

                    b.Navigation("Familiar");

                    b.Navigation("Historia");

                    b.Navigation("Maestro");

                    b.Navigation("Tutor");
                });
#pragma warning restore 612, 618
        }
    }
}
